import { defineConfig } from "vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { nitro } from "nitro/vite";
import viteReact from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import tsConfigPaths from "vite-tsconfig-paths";

// TanStack Start (same framework/pattern as Hönskoll, Studieplan, Quick Job Fit
// and Snap & Savor) — assembled from the official packages directly rather than
// the sibling apps' @lovable.dev/vite-tanstack-config wrapper, since that wrapper
// mainly adds Lovable-sandbox-preview plumbing (HMR bridge, asset proxy, dev
// telemetry) this repo — managed via GitHub/Claude Code, not Lovable — never runs
// inside. Deploys to Vercel via Nitro's "vercel" preset, matching this app's
// existing Vercel project.
//
// PWA support (public/sw.js, public/manifest.webmanifest) is hand-written
// rather than generated by vite-plugin-pwa — see public/sw.js for why.
export default defineConfig({
  plugins: [
    tailwindcss(),
    tsConfigPaths({ projects: ["./tsconfig.json"] }),
    tanstackStart({ server: { entry: "server" } }),
    nitro({ preset: "vercel" }),
    viteReact(),
  ],
  resolve: {
    alias: {
      "@": new URL("./src", import.meta.url).pathname,
    },
  },
  server: {
    host: true,
    port: 5173,
  },
});
