/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedInstallningarRouteImport } from './routes/_authenticated/installningar'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedSkordRouteImport } from './routes/_authenticated/skord'
import { Route as AuthenticatedFeedbackIdRouteImport } from './routes/_authenticated/feedback.$id'
import { Route as AuthenticatedVaxterIndexRouteImport } from './routes/_authenticated/vaxter.index'
import { Route as AuthenticatedVaxterNyRouteImport } from './routes/_authenticated/vaxter.ny'
import { Route as AuthenticatedVaxterIdIndexRouteImport } from './routes/_authenticated/vaxter.$id.index'
import { Route as AuthenticatedVaxterIdRedigeraRouteImport } from './routes/_authenticated/vaxter.$id.redigera'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstallningarRoute =
  AuthenticatedInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkordRoute = AuthenticatedSkordRouteImport.update({
  id: '/skord',
  path: '/skord',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackIdRoute = AuthenticatedFeedbackIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFeedbackRoute,
} as any)
const AuthenticatedVaxterIndexRoute =
  AuthenticatedVaxterIndexRouteImport.update({
    id: '/vaxter/',
    path: '/vaxter/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVaxterNyRoute = AuthenticatedVaxterNyRouteImport.update({
  id: '/vaxter/ny',
  path: '/vaxter/ny',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaxterIdIndexRoute =
  AuthenticatedVaxterIdIndexRouteImport.update({
    id: '/vaxter/$id/',
    path: '/vaxter/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVaxterIdRedigeraRoute =
  AuthenticatedVaxterIdRedigeraRouteImport.update({
    id: '/vaxter/$id/redigera',
    path: '/vaxter/$id/redigera',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/logga-in': typeof LoggaInRoute
  '/feedback': typeof AuthenticatedFeedbackRouteWithChildren
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/skord': typeof AuthenticatedSkordRoute
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/vaxter/ny': typeof AuthenticatedVaxterNyRoute
  '/vaxter/': typeof AuthenticatedVaxterIndexRoute
  '/vaxter/$id/redigera': typeof AuthenticatedVaxterIdRedigeraRoute
  '/vaxter/$id/': typeof AuthenticatedVaxterIdIndexRoute
}
export interface FileRoutesByTo {
  '/logga-in': typeof LoggaInRoute
  '/feedback': typeof AuthenticatedFeedbackRouteWithChildren
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/skord': typeof AuthenticatedSkordRoute
  '/': typeof AuthenticatedIndexRoute
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/vaxter/ny': typeof AuthenticatedVaxterNyRoute
  '/vaxter': typeof AuthenticatedVaxterIndexRoute
  '/vaxter/$id/redigera': typeof AuthenticatedVaxterIdRedigeraRoute
  '/vaxter/$id': typeof AuthenticatedVaxterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/logga-in': typeof LoggaInRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRouteWithChildren
  '/_authenticated/installningar': typeof AuthenticatedInstallningarRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/skord': typeof AuthenticatedSkordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/_authenticated/vaxter/ny': typeof AuthenticatedVaxterNyRoute
  '/_authenticated/vaxter/': typeof AuthenticatedVaxterIndexRoute
  '/_authenticated/vaxter/$id/redigera': typeof AuthenticatedVaxterIdRedigeraRoute
  '/_authenticated/vaxter/$id/': typeof AuthenticatedVaxterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logga-in'
    | '/feedback'
    | '/installningar'
    | '/kalender'
    | '/skord'
    | '/feedback/$id'
    | '/vaxter/ny'
    | '/vaxter/'
    | '/vaxter/$id/redigera'
    | '/vaxter/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logga-in'
    | '/feedback'
    | '/installningar'
    | '/kalender'
    | '/skord'
    | '/'
    | '/feedback/$id'
    | '/vaxter/ny'
    | '/vaxter'
    | '/vaxter/$id/redigera'
    | '/vaxter/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/logga-in'
    | '/_authenticated/feedback'
    | '/_authenticated/installningar'
    | '/_authenticated/kalender'
    | '/_authenticated/skord'
    | '/_authenticated/'
    | '/_authenticated/feedback/$id'
    | '/_authenticated/vaxter/ny'
    | '/_authenticated/vaxter/'
    | '/_authenticated/vaxter/$id/redigera'
    | '/_authenticated/vaxter/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoggaInRoute: typeof LoggaInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/installningar': {
      id: '/_authenticated/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof AuthenticatedInstallningarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skord': {
      id: '/_authenticated/skord'
      path: '/skord'
      fullPath: '/skord'
      preLoaderRoute: typeof AuthenticatedSkordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/$id': {
      id: '/_authenticated/feedback/$id'
      path: '/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof AuthenticatedFeedbackIdRouteImport
      parentRoute: typeof AuthenticatedFeedbackRoute
    }
    '/_authenticated/vaxter/': {
      id: '/_authenticated/vaxter/'
      path: '/vaxter'
      fullPath: '/vaxter/'
      preLoaderRoute: typeof AuthenticatedVaxterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vaxter/ny': {
      id: '/_authenticated/vaxter/ny'
      path: '/vaxter/ny'
      fullPath: '/vaxter/ny'
      preLoaderRoute: typeof AuthenticatedVaxterNyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vaxter/$id/': {
      id: '/_authenticated/vaxter/$id/'
      path: '/vaxter/$id'
      fullPath: '/vaxter/$id/'
      preLoaderRoute: typeof AuthenticatedVaxterIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vaxter/$id/redigera': {
      id: '/_authenticated/vaxter/$id/redigera'
      path: '/vaxter/$id/redigera'
      fullPath: '/vaxter/$id/redigera'
      preLoaderRoute: typeof AuthenticatedVaxterIdRedigeraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFeedbackRouteChildren {
  AuthenticatedFeedbackIdRoute: typeof AuthenticatedFeedbackIdRoute
}

const AuthenticatedFeedbackRouteChildren: AuthenticatedFeedbackRouteChildren = {
  AuthenticatedFeedbackIdRoute: AuthenticatedFeedbackIdRoute,
}

const AuthenticatedFeedbackRouteWithChildren =
  AuthenticatedFeedbackRoute._addFileChildren(
    AuthenticatedFeedbackRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRouteWithChildren
  AuthenticatedInstallningarRoute: typeof AuthenticatedInstallningarRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedSkordRoute: typeof AuthenticatedSkordRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVaxterNyRoute: typeof AuthenticatedVaxterNyRoute
  AuthenticatedVaxterIndexRoute: typeof AuthenticatedVaxterIndexRoute
  AuthenticatedVaxterIdRedigeraRoute: typeof AuthenticatedVaxterIdRedigeraRoute
  AuthenticatedVaxterIdIndexRoute: typeof AuthenticatedVaxterIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRouteWithChildren,
  AuthenticatedInstallningarRoute: AuthenticatedInstallningarRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedSkordRoute: AuthenticatedSkordRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVaxterNyRoute: AuthenticatedVaxterNyRoute,
  AuthenticatedVaxterIndexRoute: AuthenticatedVaxterIndexRoute,
  AuthenticatedVaxterIdRedigeraRoute: AuthenticatedVaxterIdRedigeraRoute,
  AuthenticatedVaxterIdIndexRoute: AuthenticatedVaxterIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoggaInRoute: LoggaInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
